[[constraint]]
  branch = "master"
  name = "github.com/gotk3/gotk3"

[[constraint]]
  name = "github.com/yawning/bulb"
  source = "github.com/nogoegst/bulb"
  version = "0.1.0"

[[constraint]]
  name = "github.com/nogoegst/byteqr"
  version = "1.1.0"

[[constraint]]
  name = "github.com/nogoegst/fileserver"
  version = "1.0.0"

[[constraint]]
  name = "github.com/nogoegst/onionutil"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/nogoegst/terminal"

[[constraint]]
  name = "github.com/nogoegst/tlspin"
  version = "2.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"

[[constraint]]
  branch = "master"
  name = "rsc.io/qr"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
